plugins {
    alias(libs.plugins.android.library)
}

android {
    namespace 'com.github.alibehrozi.wave.microdsp'
    compileSdk {
        version = release(37)
    }

    defaultConfig {
        minSdk 30

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        externalNativeBuild {
            cmake {
                cppFlags "-std=c++17 -O2"
            }
        }
    }

    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
            version "3.22.1"
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    testOptions {
        unitTests.returnDefaultValues = true
    }
}

dependencies {

    implementation libs.core
    implementation libs.annotation

    // Unit Testing
    testImplementation libs.junit

    // Android Instrumentation Testing
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.ext.junit
}